export default [
  { id: 1, name: 'iPhone 15', category: 'Телефони', description: 'Останній смартфон від Apple', price: 45000, image: '/images/iphone-15.png' },
  { id: 2, name: 'Samsung Galaxy S24', category: 'Телефони', description: 'Потужний Android смартфон', price: 35000, image: '/images/samsung-galaxy-s24.png' },
  { id: 3, name: 'Google Pixel 8 Pro', category: 'Телефони', description: 'Смартфон з чистим Android і камерою преміум класу', price: 27000, image: '/images/pixel-8-pro.png' },
  { id: 4, name: 'OnePlus 12', category: 'Телефони', description: 'Швидкий флагман із потужною зарядкою', price: 31000, image: '/images/OnePlus-12.png' },
  { id: 5, name: 'Xiaomi 14 Ultra', category: 'Телефони', description: 'Смартфон з професійною камерою та великим дисплеєм', price: 34000, image: '/images/xiaomi-14-ultra.png' },
  { id: 6, name: 'AirPods Pro', category: 'Навушники', description: 'Бездротові навушники з шумозаглушенням для подорожей та роботи', price: 8000, image: '/images/airpods-pro.png' },
  { id: 7, name: 'Sony WH-1000XM5', category: 'Навушники', description: 'Навушники з активним шумозаглушенням і м’якими амбушюрами', price: 12000, image: '/images/sony-wh-1000xm5.png' },
  { id: 8, name: 'Bose QuietComfort Earbuds', category: 'Навушники', description: 'Преміальні бездротові навушники для звуку без шуму', price: 11000, image: '/images/bose-qc-earbuds.png' },
  { id: 9, name: 'Samsung Galaxy Buds2 Pro', category: 'Навушники', description: 'Компактні навушники з глибоким звуком і комфортним дизайном', price: 7400, image: 'https://via.placeholder.com/300x250?text=Galaxy+Buds2+Pro' },
  { id: 10, name: 'AirPods Max', category: 'Навушники', description: 'Преміальні накладні навушники з чудовим звуком', price: 22000, image: 'https://via.placeholder.com/300x250?text=AirPods+Max' },
  { id: 11, name: 'MacBook Air', category: 'Ноутбуки', description: 'Легкий та потужний ноутбук для щоденної роботи', price: 60000, image: 'https://via.placeholder.com/300x250?text=MacBook+Air' },
  { id: 12, name: 'Dell XPS 13', category: 'Ноутбуки', description: 'Ноутбук для підвищеної продуктивності та мобільності', price: 54000, image: 'https://via.placeholder.com/300x250?text=Dell+XPS+13' },
  { id: 13, name: 'Microsoft Surface Laptop', category: 'Ноутбуки', description: 'Стильний ноутбук з сенсорним екраном для бізнесу', price: 52000, image: 'https://via.placeholder.com/300x250?text=Surface+Laptop' },
  { id: 14, name: 'Huawei MateBook 14', category: 'Ноутбуки', description: 'Компактний ноутбук для бізнесу та творчості', price: 43000, image: 'https://via.placeholder.com/300x250?text=MateBook+14' },
  { id: 15, name: 'Lenovo ThinkPad X1', category: 'Ноутбуки', description: 'Надійний ноутбук для бізнесу з преміальною клавіатурою', price: 61000, image: 'https://via.placeholder.com/300x250?text=ThinkPad+X1' },
  { id: 16, name: 'iPad Pro', category: 'Планшети', description: 'Планшет для роботи, творчості та розваг', price: 41000, image: 'https://via.placeholder.com/300x250?text=iPad+Pro' },
  { id: 17, name: 'Samsung Galaxy Tab S9', category: 'Планшети', description: 'Планшет для мультимедіа та роботи з яскравим дисплеєм', price: 28000, image: 'https://via.placeholder.com/300x250?text=Galaxy+Tab+S9' },
  { id: 18, name: 'Xiaomi Pad 6', category: 'Планшети', description: 'Стильний планшет із великим екраном для роботи та читання', price: 22000, image: 'https://via.placeholder.com/300x250?text=Xiaomi+Pad+6' },
  { id: 19, name: 'Microsoft Surface Pro 9', category: 'Планшети', description: 'Гібридний планшет для офісу та подорожей', price: 45000, image: 'https://via.placeholder.com/300x250?text=Surface+Pro+9' },
  { id: 20, name: 'Lenovo Tab P12 Pro', category: 'Планшети', description: 'Планшет з потужним процесором і яскравим екраном', price: 26000, image: 'https://via.placeholder.com/300x250?text=Tab+P12+Pro' },
  { id: 21, name: 'Apple Watch Series 9', category: 'Годинники', description: 'Смарт-годинник для активного життя', price: 16000, image: 'https://via.placeholder.com/300x250?text=Apple+Watch+9' },
  { id: 22, name: 'Samsung Galaxy Watch 7', category: 'Годинники', description: 'Розумний годинник з детальними віджетами', price: 14000, image: 'https://via.placeholder.com/300x250?text=Galaxy+Watch+7' },
  { id: 23, name: 'Garmin Fenix 7', category: 'Годинники', description: 'Годинник для спорту та активного відпочинку', price: 22000, image: 'https://via.placeholder.com/300x250?text=Fenix+7' },
  { id: 24, name: 'Huawei Watch GT 4', category: 'Годинники', description: 'Стильний годинник із тривалим зарядом батареї', price: 9500, image: 'https://via.placeholder.com/300x250?text=Watch+GT+4' },
  { id: 25, name: 'Amazfit GTR 4', category: 'Годинники', description: 'Гаджет з детальною фітнес-аналітикою', price: 7800, image: 'https://via.placeholder.com/300x250?text=GTR+4' },
  { id: 26, name: 'JBL Charge 5', category: 'Аксесуари', description: 'Портативна акустика з глибоким звуком', price: 5200, image: 'https://via.placeholder.com/300x250?text=JBL+Charge+5' },
  { id: 27, name: 'GoPro Hero 12', category: 'Аксесуари', description: 'Екшн-камера для подорожей і спорту', price: 15000, image: 'https://via.placeholder.com/300x250?text=GoPro+Hero+12' },
  { id: 28, name: 'Anker PowerCore 20000', category: 'Аксесуари', description: 'Потужний портативний зарядний пристрій', price: 1800, image: 'https://via.placeholder.com/300x250?text=PowerCore+20000' },
  { id: 29, name: 'Logitech MX Master 3', category: 'Аксесуари', description: 'Ергономічна мишка для професійної роботи', price: 4200, image: 'https://via.placeholder.com/300x250?text=MX+Master+3' },
  { id: 30, name: 'Kindle Paperwhite', category: 'Аксесуари', description: 'Електронна книга з підсвіткою', price: 6200, image: 'https://via.placeholder.com/300x250?text=Kindle+Paperwhite' },
  { id: 31, name: 'Nokia XR20', category: 'Телефони', description: 'Надійний смартфон для активного використання', price: 19000, image: 'https://via.placeholder.com/300x250?text=Nokia+XR20' },
  { id: 32, name: 'Realme GT 6', category: 'Телефони', description: 'Ігровий смартфон з високою продуктивністю', price: 24000, image: 'https://via.placeholder.com/300x250?text=Realme+GT+6' },
  { id: 33, name: 'Sony Xperia 1 VI', category: 'Телефони', description: 'Смартфон з чудовою камерою та дисплеєм', price: 39000, image: 'https://via.placeholder.com/300x250?text=Xperia+1+VI' },
  { id: 34, name: 'JBL Tune 770NC', category: 'Навушники', description: 'Накладні навушники з шумозаглушенням', price: 6500, image: 'https://via.placeholder.com/300x250?text=JBL+Tune+770NC' },
  { id: 35, name: 'Sennheiser Momentum True Wireless 4', category: 'Навушники', description: 'Музичні навушники з якісним звуком', price: 11500, image: 'https://via.placeholder.com/300x250?text=Momentum+TW+4' },
  { id: 36, name: 'Beats Studio Buds', category: 'Навушники', description: 'Компактні і гучні бездротові навушники', price: 7200, image: 'https://via.placeholder.com/300x250?text=Beats+Studio+Buds' },
  { id: 37, name: 'ASUS ZenBook 14', category: 'Ноутбуки', description: 'Тонкий ноутбук з великим часом роботи батареї', price: 47000, image: 'https://via.placeholder.com/300x250?text=ZenBook+14' },
  { id: 38, name: 'HP Spectre x360', category: 'Ноутбуки', description: 'Перетворюваний ноутбук з сенсорним екраном', price: 57000, image: 'https://via.placeholder.com/300x250?text=Spectre+x360' },
  { id: 39, name: 'Acer Swift 5', category: 'Ноутбуки', description: 'Легкий ноутбук для мобільної роботи', price: 41000, image: 'https://via.placeholder.com/300x250?text=Swift+5' },
  { id: 40, name: 'Samsung Galaxy Tab A9', category: 'Планшети', description: 'Доступний планшет для розваг та веб-серфінгу', price: 16000, image: 'https://via.placeholder.com/300x250?text=Tab+A9' },
  { id: 41, name: 'Amazon Fire HD 10', category: 'Планшети', description: 'Планшет з великим дисплеєм для читання і відео', price: 12500, image: 'https://via.placeholder.com/300x250?text=Fire+HD+10' },
  { id: 42, name: 'Apple iPad Mini', category: 'Планшети', description: 'Компактний планшет для подорожей і нотаток', price: 21000, image: 'https://via.placeholder.com/300x250?text=iPad+Mini' },
  { id: 43, name: 'Samsung Galaxy Watch 6 Classic', category: 'Годинники', description: 'Класичний стильний смарт-годинник', price: 17800, image: 'https://via.placeholder.com/300x250?text=Watch+6+Classic' },
  { id: 44, name: 'Fitbit Versa 4', category: 'Годинники', description: 'Фітнес-годинник з трекінгом активності', price: 9200, image: 'https://via.placeholder.com/300x250?text=Versa+4' },
  { id: 45, name: 'Polar Vantage M3', category: 'Годинники', description: 'Годинник для спорту з GPS і вимірюванням серцебиття', price: 13200, image: 'https://via.placeholder.com/300x250?text=Vantage+M3' },
  { id: 46, name: 'Nomad USB-C Hub', category: 'Аксесуари', description: 'Мультипортовий хаб для ноутбука', price: 2900, image: 'https://via.placeholder.com/300x250?text=USB-C+Hub' },
  { id: 47, name: 'Razer BlackWidow V4', category: 'Аксесуари', description: 'Механічна клавіатура для геймерів', price: 7800, image: 'https://via.placeholder.com/300x250?text=BlackWidow+V4' },
  { id: 48, name: 'SanDisk Extreme Portable SSD', category: 'Аксесуари', description: 'Швидкий зовнішній накопичувач для зберігання файлів', price: 5200, image: 'https://via.placeholder.com/300x250?text=Extreme+SSD' }
]
